services:
  backend:
    build: ./backend-AI
    ports:
      - "8000:8000"
    env_file:
      - ./backend-AI/.env
    volumes:
      - ./backend-AI/app:/app
    depends_on:
      - frontend
    networks:
      - ai-app

  frontend:
    build:
      context: ./frontend-AI
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./frontend-AI:/src
    networks:
      - ai-app
networks:
  ai-app:
    driver: bridge