# fly.toml for AI Content Generator Backend
app = "ai-content-backend"
primary_region = "iad"

[build]
  dockerfile = "backend-AI/Dockerfile"

[env]
  PORT = "8000"
  ENVIRONMENT = "production"

[http_service]
  internal_port = 8000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]

[[http_service.checks]]
  grace_period = "10s"
  interval = "30s"
  method = "GET"
  timeout = "5s"
  path = "/health"

[machine]
  cpu_kind = "shared"
  cpus = 1
  memory_mb = 512 